version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongo-data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API S3-compatible
      - "9001:9001"   # Console UI (access via http://localhost:9001)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  mongo-data:
  minio-data:
